### ISSUE TITLE
Doesnt start on Windows

### ISSUE THREAD

**Issue by KoninMikhail** [itsjavi/turborepo-react-next#1]
Hello. Houston we have a problem with linux dependecies.

After `git clone [repo uri]`, 
im using `yarn install` and `bash dev.sh cli` (with git bash), 
in response i get 
```
Cannot find module '/usr/src/app/apps/cli/dist/index.mjs'
```
if use `bash dev.sh yarn`, installation will complete, 
however on docker start, project exite with code 1.
esbuild causes an error in the logs

**Comment by itsjavi** [comment]
hi, can you try to run `yarn build` before using the CLI?

I think that's the issue. I should improve this a little more & also the docs.

**Comment by KoninMikhail** [comment]
im create screenshots ) give it https://drive.google.com/file/d/15FBtz9a8EJdwV2DdyvNXvcdyNlsZBRsC/view?usp=share_link 
start with yarn gives the same result

**Comment by KoninMikhail** [comment]
important note... inside the docker image, the app folder is empty.

**Comment by KoninMikhail** [comment]
after research i realized that many commands are not compatible with windows :( for example rm in scripts

**Comment by KoninMikhail** [comment]
I solved the problem myself
